from django.contrib import admin
from .models import Profile, ContactDetail, SocialMedia, Education, Experience, CareerBreak, Service, Language, VolunteerExperience, Project, Certification, Recommendation, Publication, Patent, HonorAward, TestScore, Organization

admin.site.register(Profile)
admin.site.register(ContactDetail)
admin.site.register(SocialMedia)
admin.site.register(Education)
admin.site.register(Experience)
admin.site.register(CareerBreak)
admin.site.register(Service)
admin.site.register(Language)
admin.site.register(VolunteerExperience)
admin.site.register(Project)
admin.site.register(Certification)
admin.site.register(Recommendation)
admin.site.register(Publication)
admin.site.register(Patent)
admin.site.register(HonorAward)
admin.site.register(TestScore)
admin.site.register(Organization)
